### ISSUE TITLE
Change to minimum ruby version on a patch level change

### ISSUE THREAD

**Issue by jeremiahishere** [chef/mixlib-config#54]
I just ran into an issue while trying to install the chef gem.  It requires mixlib-config version ~> 2.0.  Between version 2.2.4 and 2.2.5, there was an undocumented change to require ruby version 2.2.  This line was added to the gemspec.

`s.required_ruby_version = ">= 2.2"`

The change is a little confusing because version 2.2.4 did not include the line.  The git history suggests that this pull request from 2016 includes the change: https://github.com/chef/mixlib-config/pull/46.  It was merged to master but didn't show up until minor patch bump 2.2.5.

This change breaks systems using older versions of chef and older version of ruby.  Would it be possible to make the change in minimum ruby version a major level release?

**Comment by coderanger** [comment]
I'm mostly hands off over on the mixlib side of things, but we did a broad pass over all our projects to make this requirement more explicit. Ruby 2.1 exited upstream support in April 2017 so we can no longer support it either. If you are receiving third-party commercial support for Ruby, you should contact that vendor or team about supporting this gem too.

**Comment by lamont-granquist** [comment]
Modern versions of bundler don't break with this, and it is actually a large annoyance to major version bump the entire universe just to drop support for old ruby versions.  We also generally state that we only support omnibus build version of chef and chef-dk which should pin mixlib-config, so you shouldn't be pulling new version down to old omnibus versions.  I suspect we're going to allow the old versions of bundler to fade away rather than confining dropping old ruby version support to major version bumps.  For Gemfile-installed chef-client you're going to have to occasionally maintain pins.   This happened to us when activesupport and rack dropped support to ruby 2.1 and we had to run around to many dozens of projects and pin everything because we had gotten behind ourselves, and this is just a cost of not upgrading promptly.
